1-savol.  malumot bu, hali qayta ishlanmagan yoki izoxlanmagan xom yoki chala faktlardir, bularga misol bolishi mumkin, 
raqamlar, ismlar, sanalar, yoki narxlar vahakazolar bo`lishi mumkin.

Malumotlar bazasi- bu tartibga solingan elektron malumotlar hisoblanadi, bunga misol bank tizimlari, web site lar va harqanday 
elektron shakldagi tartiblangan malumotlar to`plamidir.

relational database- bu malumotlarni satr yoki ustun shakildagi jadvallarda saqlovchi turdagi
malumotlar bazasidir, har bir jadvalda muayyan turdagi malumotlar tartiblab saqlangan boladi, foydalanish uchun qulaylik uchun
bunday turdagi malumotlarni boshqarish uchun sql dan foydalaniladi.

table- bu relational malumotlar bazasidagi tuzilma bo`lib,unda malumotlar tasrlar va ustunlar shaklda tashkil qlininadi.
har bir satr bitta yozuv va 
va har bitta ustun ea shu yozuvga oid atribyutlarni tashkil qiladi.
masalan. mijoz id si, ism familyasi, email vahakazolar.

2- savol:   1 sql sever,  2. T-SQL 3. XAFSIZLIK VA AUTENTIFIKATSIYA 4. YUQORI MAVJUDLIK VA AVARIYA HOLATLARIDAN TIKLANISH
BOSHQA MICROSOFT XIZMATLARI BILAN INTEGIRATSIYA.

3- SAVOL KIRISH USULIDAGI FARQ, MISOL UCHUN, WINDOWS AUTENTIFICATION DA, FOYDALANUVCHI WINDOWS TIZIMIGA KOMPYUTERGA KIRGAN
LOGIN ORQALI AVTOMATIK RAVISHDA KIRADI AMMA SQL SERVER AUTENTIFICATION DA , FOYDALANUVCHI SQL SERVER UCHUN
ALOHIDA LOGIN VA PAROL KITADI.
2 CHI FARQI, PAROL BOSHQARUVI; WINDOWS AUTENTIFACTION DA WINDOS TOMONIDAN BOSHQARILADI,AMMO SQL SERVER AUTENTIFICATION DA ESA
SQL SERVER
TOMONIDAN BOSHQARILADI.
3 CHI FARQ, WINDOWS AUTENTIFICATION DA , FAQAT WINDOWS TIZIMI BILAN ISHLAYDI,AMMO SQL AUTENTIFICATION DA ESA LINUX,WEB ILOVALAR
MOBIL ILOVALAR BILAN HAM ISHLASHI MUMKIN

4- SAVOL  CREATE DATABASE SCHOOLIDB;

 5- SAVOL CREATE TABLE STUDENTS (STUDENT_ID INT PRIMARY KEY, FIRSTNAME VARCHAR(50),AGE INT)
 6- SAVOL  SQL( STRUCTURED QUERY LANGUAGE) YANI MALUMOTLAR BAZASINI BOSHQARISH, VA TAHRIRLASH UCHUN ISHLATILINADIGAN BUYRUQLAR TILI.
 SQL SERVER ESA MICROSOFT TOMONIDAN ISHLAB CHIQARILGAN RELATIONAL MALUMOTLAR BAZASI TIZIMI(RDBMS), BU ASOSAN DVIGATEL,
 YANI MALUMOTLAR SHUYERDA
 SAQLANADI VA BOSHQARILADI.
 SSMS(SQL SERVER MANAGEMENT STUDIO) SQL SERVERNI BOSHQARISH, JADVAL YARATISH, SO`ROVLAR YOZISH, VA HISOBKITOBLARNI 
 KO`RISH UCHUN FOYDALANILADI.
 7 - SAVOL  DQL: DATA QUERY LANGUAGE YANI MALUMOTLARNI BAZADAN QIDIRADI. MISOL UCHUN SELECT * FROM STUDENTS;
 DML: MALUMOTLARNI BOSHQARISH TILI. ASOSIY BUYRUQLARI:  INSERT, UPDATE, DELETE
 MISOL UCHUN:  INSERT INTO STUDENTS (NAME, AGE) VALUES('ALI',20);
  UPDATE STUDENTS SET AGE = 21 WHERE NAME ='ALI';
  DELETE FROM STUDENTS WHERE NAME ='ALI';
  DDL: MALUMOTLAR TUZULMASINI BELGILOVCHI TILI.  
  ASOSIY BUYRUQLARI
  CREATE, ALTER, DROP
  MISOL UCHUN  
  ALTER STUDENTS ADD EMAIL VARCHAR(100);
  CREATE TABLE STUDENTS (ID INT, NAME VARCHAR(50), AGE INT)
  DROP TABLE STUDENTS;
  DCL: DATA CONTROL LANGUAGE VAZIFASI: FOYDALANUVCHILARGA BUYRUQLAR BERISH YOKI OLIB TASHLASH
  ASOSIY BUYRUQLARI:
  GRANT, REVOKE

  MISOL UCHUN:  GRANT SELECT ON STUDENTS TO USUER1;
  REVOKE SELECT ON STUDENTS FROM USER1;

  TCL:  TRANSACTION CONTROL LANGUAGE:  VAZIFASI:  MALUMOTLAR USTIDA BAJARILGAN OPERATSIYALARNI SAQLASH, BEKOR QILISH YOKI VAQTINCHA SAQLASH

  ASOSIY BUYRUQLARI.  COMMIT, ROLLBACK, SAVEPOINT
  MISOL UCHUN:
  BEGIN TRANSACTION UPDATE STUDENTS SET AGE =22 WHERE NAME 'ALI';
  COMMIT;


  BEGIN TRANSACTION;
  DELETE FROM STUDENTS WHERE AGE<18 ;
  ROLLBACK;

  8- SAVOL:

  INSERT INTO STUDENTS (ID,NAME,AGE)
  VALUES(1,'SHAXBOZ',20),(2,'MIRSHOD',33),(3,'SHAMSHOD',19);
